# log failure

    Code
      capture.output(log_failure(foobar))
    Condition
      Error:
      ! object 'foobar' not found

